from enum import Enum


class ReasonCode(str, Enum):
    DELIVERED_SUCCESS = "DELIVERED_SUCCESS"

    RESOLVER_EXPLICIT = "RESOLVER_EXPLICIT"
    RESOLVER_MATCHED = "RESOLVER_MATCHED"
    RESOLVER_AMBIGUOUS = "RESOLVER_AMBIGUOUS"
    RESOLVER_NO_MATCH = "RESOLVER_NO_MATCH"

    TZ_EXPLICIT = "TZ_EXPLICIT"
    TZ_HOUSEHOLD_DEFAULT = "TZ_HOUSEHOLD_DEFAULT"
    TZ_FALLBACK_USED = "TZ_FALLBACK_USED"
    TZ_MISSING = "TZ_MISSING"

    FAILED_PROVIDER_TRANSIENT = "FAILED_PROVIDER_TRANSIENT"
    FAILED_PROVIDER_PERMANENT = "FAILED_PROVIDER_PERMANENT"
    FAILED_CONFIG_INVALID_TARGET = "FAILED_CONFIG_INVALID_TARGET"
    FAILED_CAPABILITY_UNSUPPORTED = "FAILED_CAPABILITY_UNSUPPORTED"
    FAILED_RETRY_EXHAUSTED = "FAILED_RETRY_EXHAUSTED"
    SUPPRESSED_QUIET_HOURS = "SUPPRESSED_QUIET_HOURS"

    UPDATED_REGENERATED = "UPDATED_REGENERATED"
    CANCEL_INVALIDATED = "CANCEL_INVALIDATED"
    BLOCKED_CONFIRMATION_REQUIRED = "BLOCKED_CONFIRMATION_REQUIRED"
    VERSION_CONFLICT_RETRY = "VERSION_CONFLICT_RETRY"

    RECOVERY_RECONCILED = "RECOVERY_RECONCILED"
    FAIRNESS_BOUND_EXCEEDED = "FAIRNESS_BOUND_EXCEEDED"
    DB_RECONNECT_EXHAUSTED = "DB_RECONNECT_EXHAUSTED"
    STARTUP_VALIDATION_FAILED = "STARTUP_VALIDATION_FAILED"
    SHUTDOWN_GRACE_EXCEEDED = "SHUTDOWN_GRACE_EXCEEDED"

    CAPTURE_ONLY_BLOCKED = "CAPTURE_ONLY_BLOCKED"
