from enum import Enum


class ReasonCode(str, Enum):
    RESOLVER_EXPLICIT = "RESOLVER_EXPLICIT"
    RESOLVER_MATCHED = "RESOLVER_MATCHED"
    RESOLVER_AMBIGUOUS = "RESOLVER_AMBIGUOUS"
    RESOLVER_NO_MATCH = "RESOLVER_NO_MATCH"

    TZ_EXPLICIT = "TZ_EXPLICIT"
    TZ_HOUSEHOLD_DEFAULT = "TZ_HOUSEHOLD_DEFAULT"
    TZ_FALLBACK_USED = "TZ_FALLBACK_USED"
    TZ_MISSING = "TZ_MISSING"

    DELIVERED = "DELIVERED"
    FAILED_PROVIDER = "FAILED_PROVIDER"
    FAILED_RETRY_EXHAUSTED = "FAILED_RETRY_EXHAUSTED"
    SUPPRESSED_QUIET_HOURS = "SUPPRESSED_QUIET_HOURS"

    UPDATED_REGENERATED = "UPDATED_REGENERATED"
    CANCEL_INVALIDATED = "CANCEL_INVALIDATED"
    BLOCKED_CONFIRMATION_REQUIRED = "BLOCKED_CONFIRMATION_REQUIRED"

    RECOVERY_RECONCILED = "RECOVERY_RECONCILED"
    CAPTURE_ONLY_BLOCKED = "CAPTURE_ONLY_BLOCKED"
